# Generated by Django 4.0.4 on 2022-04-24 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporative_net', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='order_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='corporative_net.orders', verbose_name='order_id'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='executor_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='corporative_net.workers', verbose_name='executor_id'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('passed', 'passed'), ('failed', 'failed'), ('not ready', 'not ready')], default='not ready', max_length=64),
        ),
        migrations.AlterField(
            model_name='workers',
            name='active_order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='corporative_net.orders', verbose_name='active_order'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='corporative_net.posts', verbose_name='post_id'),
        ),
    ]
