# Generated by Django 4.0.4 on 2022-04-24 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=255)),
                ('discription', models.TextField(max_length=511)),
                ('client_sum', models.IntegerField(default=0, verbose_name='client_sum')),
                ('status', models.CharField(choices=[('passed', 'Available to borrow'), ('failed', 'Borrowed by someone'), ('not ready', 'Archived - not available anymore')], default='not ready', max_length=64)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('discription', models.TextField(max_length=511, verbose_name='discription')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=64)),
                ('active_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corporative_net.orders', verbose_name='workers')),
                ('post_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='corporative_net.posts', verbose_name='post_id')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='executor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corporative_net.workers', verbose_name='executor_id'),
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('order_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='corporative_net.orders', verbose_name='order_id')),
            ],
        ),
    ]
