# Generated by Django 4.0.4 on 2022-05-03 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporative_net', '0002_remove_clients_order_id_remove_workers_active_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='lastname',
            field=models.CharField(max_length=255, verbose_name='lastname'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(max_length=64, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='client_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='corporative_net.clients', verbose_name='client_id'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
