# Generated by Django 4.0.4 on 2022-05-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporative_net', '0003_alter_clients_email_alter_clients_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypt_one', models.CharField(max_length=255, verbose_name='crypt_one')),
                ('price_one', models.IntegerField(default=0)),
                ('crypt_two', models.CharField(max_length=255, verbose_name='crypt_two')),
                ('price_two', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'prices',
            },
        ),
    ]
